# Generated by Django 4.0.5 on 2022-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Repository', models.TextField(max_length=1000)),
                ('Stars', models.IntegerField(null=True)),
                ('Contributors', models.IntegerField(null=True)),
                ('Programming_Language', models.TextField(help_text='Programming Language', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
