# Generated by Django 4.0.5 on 2022-07-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlui', '0002_transformer_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_no', models.CharField(max_length=500)),
                ('Billing_Month', models.CharField(max_length=6)),
                ('current_bill_amount', models.FloatField()),
                ('previous_bill_amount', models.FloatField()),
                ('units_consumed', models.IntegerField(null=True)),
                ('consumer_name', models.CharField(max_length=500)),
            ],
        ),
    ]
